name: Build study image

on: [push, workflow_dispatch]

jobs:
  create-study-image:
    if: github.event.pull_request.draft != true  # #GreenIT
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: LinqLover/create-image@master
        id: create-image
        with:
          prepare-script: ./scripts/prepareStudyImage.st
      - uses: actions/upload-artifact@master
        with:
          name: image
          path: ${{ steps.create-image.outputs.bundle-path }}
