name: Release

on: [push, workflow_dispatch]

jobs:
  create-image:
    if: github.event.pull_request.draft != true  # #GreenIT
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: LinqLover/create-image@master
        id: create-image
        with:
          prepare-script: ./scripts/prepareImage.st
      - uses: actions/upload-artifact@master
        with:
          name: image
          path: ${{ steps.create-image.outputs.bundle-path }}
  release-image:
    needs: create-image
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d-%H%M%S')"
      - uses: actions/download-artifact@master
        with:
          name: image
      - run: mv Squeak*.zip Sonyx-${{ steps.date.outputs.date }}.zip
      - uses: softprops/action-gh-release@v1
        with:
          tag_name: untagged-${{ steps.date.outputs.date }}
          body: ${{ github.event.head_commit.message }}
          files: Sonyx-*.zip
          fail_on_unmatched_files: true
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ github.token }}
